In [2]:
# 2019-12-08南京部分检测站点的天气指标
polls = {
    "sites": ["迈皋桥", "草场门", "浦口", "奥体中心", "仙林大学城"],
    "AQI": [55, 75, 69, 74, 58],
    "PM25": [30, 54, 47, 40, 27],
    "SO2": [10, 15, 13, 17, 10]
}
# 站点的信息
sites = {
    "names": ["迈皋桥", "草场门", "浦口", "奥体中心", "玄武湖"],
    "regions": ["栖霞区", "鼓楼区", "浦口区", "建邺区", "玄武区"],
    "weather": ["晴", "晴", "多云", "阴", "晴"]
}
'''
pd.merge(left, right, how='inner', on=None, left_on=None, right_on=None,
         left_index=False, right_index=False)
left：拼接左侧的DataFrame对象；
right：拼接右侧的DataFrame对象；
on：待关联的同名列名，存在于左右两个DataFrame对象中；
how：连接方式，inner（默认），其他可选：outer、left、right ；
left_on：左侧DataFarme中用作连接键的列名；
right_on：右侧DataFarme中用作连接键的列；
left_index：将左侧的行索引用作其连接键；
right_index：将右侧的行索引用作其连接键；
根据连接方式的不同（how字段），可以分为左连接（left）、右连接（right）、
内连接（inner）、外连接（outer）共4种情况。
'''
import pandas as pd
# 读取数据集，把字典格式转变为DataFrame格式
df_polls = pd.DataFrame(polls)
df_sites = pd.DataFrame(sites)
print(df_polls)
print(df_sites)

   sites  AQI  PM25  SO2
0    迈皋桥   55    30   10
1    草场门   75    54   15
2     浦口   69    47   13
3   奥体中心   74    40   17
4  仙林大学城   58    27   10
  names regions weather
0   迈皋桥     栖霞区       晴
1   草场门     鼓楼区       晴
2    浦口     浦口区      多云
3  奥体中心     建邺区       阴
4   玄武湖     玄武区       晴

In [3]:
# 总览左右两侧的DataFrame，我们发现并没有共同的列，所以这里我无法通过指定on字段来进行关联；
# 对应的，我们分别指定left_on和right_on
pd.merge(df_polls, df_sites, left_on='sites', right_on='names', how='left')

   sites  AQI  PM25  SO2 names regions weather
0    迈皋桥   55    30   10   迈皋桥     栖霞区       晴
1    草场门   75    54   15   草场门     鼓楼区       晴
2     浦口   69    47   13    浦口     浦口区      多云
3   奥体中心   74    40   17  奥体中心     建邺区       阴
4  仙林大学城   58    27   10   NaN     NaN     NaN

In [4]:
# 右连接的右侧连接键是names，因此以names列为基准，其他列往上拼接，无对应值则为Nan
# 在默认的情况下，merge函数会保留全部的列字段
pd.merge(df_polls, df_sites, left_on='sites', right_on='names', how='right')

  sites   AQI  PM25   SO2 names regions weather
0   迈皋桥  55.0  30.0  10.0   迈皋桥     栖霞区       晴
1   草场门  75.0  54.0  15.0   草场门     鼓楼区       晴
2    浦口  69.0  47.0  13.0    浦口     浦口区      多云
3  奥体中心  74.0  40.0  17.0  奥体中心     建邺区       阴
4   NaN   NaN   NaN   NaN   玄武湖     玄武区       晴

In [5]:
# 默认how='inner'
pd.merge(df_polls, df_sites, left_on='sites', right_on='names')

  sites  AQI  PM25  SO2 names regions weather
0   迈皋桥   55    30   10   迈皋桥     栖霞区       晴
1   草场门   75    54   15   草场门     鼓楼区       晴
2    浦口   69    47   13    浦口     浦口区      多云
3  奥体中心   74    40   17  奥体中心     建邺区       阴

In [6]:
pd.merge(df_polls, df_sites, left_on='sites', right_on='names', how='outer')

   sites   AQI  PM25   SO2 names regions weather
0    迈皋桥  55.0  30.0  10.0   迈皋桥     栖霞区       晴
1    草场门  75.0  54.0  15.0   草场门     鼓楼区       晴
2     浦口  69.0  47.0  13.0    浦口     浦口区      多云
3   奥体中心  74.0  40.0  17.0  奥体中心     建邺区       阴
4  仙林大学城  58.0  27.0  10.0   NaN     NaN     NaN
5    NaN   NaN   NaN   NaN   玄武湖     玄武区       晴

In [7]:
# 定义左侧数据集
df_left = pd.DataFrame({
    "sites": ["迈皋桥", "草场门", "浦口", "迈皋桥", "草场门", "浦口"],
    "date": [
        "2019-12-08", "2019-12-08", "2019-12-08", "2019-12-07", "2019-12-07",
        "2019-12-07"
    ],
    "AQI": [55, 75, 69, 45, 35, 53]
})
# 定义右侧数据集
df_right = pd.DataFrame({
    "sites": ["迈皋桥", "草场门", "迈皋桥", "草场门"],
    "date": ["2019-12-08", "2019-12-08", "2019-12-09", "2019-12-09"],
    "weather": ["晴", "晴", "多云", "阴"]
})
print(df_left)
print(df_right)

  sites        date  AQI
0   迈皋桥  2019-12-08   55
1   草场门  2019-12-08   75
2    浦口  2019-12-08   69
3   迈皋桥  2019-12-07   45
4   草场门  2019-12-07   35
5    浦口  2019-12-07   53
  sites        date weather
0   迈皋桥  2019-12-08       晴
1   草场门  2019-12-08       晴
2   迈皋桥  2019-12-09      多云
3   草场门  2019-12-09       阴

In [8]:
# sites、date两个字段均一样，才满足拼接条件。
pd.merge(df_left, df_right, on=['sites', 'date'])

  sites        date  AQI weather
0   迈皋桥  2019-12-08   55       晴
1   草场门  2019-12-08   75       晴

In [9]:
# 当数据量增大时，我们要尤其注意避免数据量呈几何级增大这种问题。
pd.merge(df_left, df_right, on='sites')

  sites      date_x  AQI      date_y weather
0   迈皋桥  2019-12-08   55  2019-12-08       晴
1   迈皋桥  2019-12-08   55  2019-12-09      多云
2   迈皋桥  2019-12-07   45  2019-12-08       晴
3   迈皋桥  2019-12-07   45  2019-12-09      多云
4   草场门  2019-12-08   75  2019-12-08       晴
5   草场门  2019-12-08   75  2019-12-09       阴
6   草场门  2019-12-07   35  2019-12-08       晴
7   草场门  2019-12-07   35  2019-12-09       阴

In [10]:
pd.merge(df_left, df_right, on=['sites', 'date'], how='outer')

  sites        date   AQI weather
0   迈皋桥  2019-12-08  55.0       晴
1   草场门  2019-12-08  75.0       晴
2    浦口  2019-12-08  69.0     NaN
3   迈皋桥  2019-12-07  45.0     NaN
4   草场门  2019-12-07  35.0     NaN
5    浦口  2019-12-07  53.0     NaN
6   迈皋桥  2019-12-09   NaN      多云
7   草场门  2019-12-09   NaN       阴

In [11]:
# 指定left_index或right_index即可轻松实现基于index的关联。
sites_with_index = pd.DataFrame(
    {"regions": ["栖霞区", "鼓楼区", "浦口区", "建邺区", "玄武区"]},
    index=["迈皋桥", "草场门", "浦口", "奥体中心", "玄武湖"])
sites_with_index

     regions
迈皋桥      栖霞区
草场门      鼓楼区
浦口       浦口区
奥体中心     建邺区
玄武湖      玄武区

In [12]:
# 左侧关联键为sites列，右侧关联键为索引
pd.merge(df_polls, sites_with_index, left_on='sites', right_index=True)

  sites  AQI  PM25  SO2 regions
0   迈皋桥   55    30   10     栖霞区
1   草场门   75    54   15     鼓楼区
2    浦口   69    47   13     浦口区
3  奥体中心   74    40   17     建邺区

In [13]:
polls_with_index = pd.DataFrame(
    {
        "AQI": [55, 75, 69, 74, 58],
        "PM25": [30, 54, 47, 40, 27],
        "SO2": [10, 15, 13, 17, 10]
    },
    index=["迈皋桥", "草场门", "浦口", "奥体中心", "仙林大学城"])
polls_with_index

       AQI  PM25  SO2
迈皋桥     55    30   10
草场门     75    54   15
浦口      69    47   13
奥体中心    74    40   17
仙林大学城   58    27   10

In [15]:
# 利用join函数实现左右DataFrame的索引关联
polls_with_index.join(sites_with_index, how='inner')

      AQI  PM25  SO2 regions
迈皋桥    55    30   10     栖霞区
草场门    75    54   15     鼓楼区
浦口     69    47   13     浦口区
奥体中心   74    40   17     建邺区

In [16]:
'''
另外一种常用的数据整合方法是concat，即我希望按照某种方式把两个规整的数据集进行拼接。
pd.concat(objs, axis=0, join='outer', keys=None)
objs：带拼接的数据集，通常以列表的形式传入；
join：可选inner、outer，含义同merge函数；
keys：定义新的分组索引，用来区分传入的数据集；
'''
new_polls = {
    "sites": ["迈皋桥", "草场门", "浦口", "奥体中心", "仙林大学城"],
    "AQI": [65, 85, 79, 78, 78],
    "PM25": [50, 74, 67, 60, 47],
    "O2": [20, 35, 23, 37, 15]
}
df_new_polls = pd.DataFrame(new_polls)
df_new_polls

   sites  AQI  PM25  O2
0    迈皋桥   65    50  20
1    草场门   85    74  35
2     浦口   79    67  23
3   奥体中心   78    60  37
4  仙林大学城   78    47  15

In [17]:
pd.concat([df_new_polls, df_polls],
          join='inner',
          keys=['2019-12-07', '2019-12-08'])

              sites  AQI  PM25
2019-12-07 0    迈皋桥   65    50
           1    草场门   85    74
           2     浦口   79    67
           3   奥体中心   78    60
           4  仙林大学城   78    47
2019-12-08 0    迈皋桥   55    30
           1    草场门   75    54
           2     浦口   69    47
           3   奥体中心   74    40
           4  仙林大学城   58    27